import type { PluginInstance, SystemMetrics, SystemInfo } from "./types";

export const mockPlugins: PluginInstance[] = [
  {
    id: "1",
    name: "udp_server",
    type: "server",
    pluginKind: "udp_server",
    status: "running",
    enabled: true,
    pinned: true,
    config: { listen: "0.0.0.0:53", entry: "seq_main" },
    metrics: { calls: 125840, avgLatency: 2.3, errorRate: 0.01, qps: 1250 },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "2",
    name: "tcp_server",
    type: "server",
    pluginKind: "tcp_server",
    status: "running",
    enabled: true,
    pinned: false,
    config: { listen: "0.0.0.0:53", entry: "seq_main", idle_timeout: 10 },
    metrics: { calls: 8420, avgLatency: 5.1, errorRate: 0.02, qps: 84 },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-18T09:15:00Z",
  },
  {
    id: "3",
    name: "doh_server",
    type: "server",
    pluginKind: "http_server",
    status: "running",
    enabled: true,
    pinned: true,
    config: {
      listen: "0.0.0.0:443",
      cert: "/etc/ssl/cert.pem",
      key: "/etc/ssl/key.pem",
      entries: [{ path: "/dns-query", exec: "seq_main" }],
    },
    metrics: { calls: 45200, avgLatency: 8.5, errorRate: 0.005, qps: 452 },
    createdAt: "2024-01-16T11:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "4",
    name: "cache_cn",
    type: "executor",
    pluginKind: "cache",
    status: "running",
    enabled: true,
    pinned: true,
    config: { size: 10000, short_circuit: true, max_positive_ttl: 300 },
    metrics: {
      calls: 180060,
      hitRate: 0.85,
      avgLatency: 0.1,
      errorRate: 0,
      qps: 1800,
    },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "5",
    name: "cache_global",
    type: "executor",
    pluginKind: "cache",
    status: "running",
    enabled: true,
    pinned: false,
    config: { size: 50000, max_positive_ttl: 600 },
    metrics: {
      calls: 95000,
      hitRate: 0.72,
      avgLatency: 0.15,
      errorRate: 0,
      qps: 950,
    },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-19T16:45:00Z",
  },
  {
    id: "6",
    name: "forward_cn",
    type: "executor",
    pluginKind: "forward",
    status: "running",
    enabled: true,
    pinned: true,
    config: {
      concurrent: 2,
      upstreams: [
        { tag: "ali", addr: "udp://223.5.5.5:53", timeout: "3s" },
        { tag: "dnspod", addr: "udp://119.29.29.29:53", timeout: "3s" },
      ],
    },
    metrics: { calls: 27000, avgLatency: 15.2, errorRate: 0.03, qps: 270 },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "7",
    name: "forward_global",
    type: "executor",
    pluginKind: "forward",
    status: "running",
    enabled: true,
    pinned: false,
    config: {
      concurrent: 2,
      upstreams: [
        { tag: "google", addr: "udp://8.8.8.8:53", timeout: "5s" },
        { tag: "cloudflare", addr: "udp://1.1.1.1:53", timeout: "5s" },
      ],
    },
    metrics: { calls: 26500, avgLatency: 45.8, errorRate: 0.05, qps: 265 },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T12:00:00Z",
  },
  {
    id: "8",
    name: "block_ads",
    type: "executor",
    pluginKind: "sequence",
    status: "running",
    enabled: true,
    pinned: false,
    config: { args: [{ matches: "$ad_domain", exec: "reject 3" }] },
    metrics: { calls: 15800, avgLatency: 0.05, errorRate: 0, qps: 158 },
    createdAt: "2024-01-16T14:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "9",
    name: "cn_domain",
    type: "matcher",
    pluginKind: "qname",
    status: "running",
    enabled: true,
    pinned: true,
    config: { args: ["&/etc/oxidns/cn_domains.txt"] },
    metrics: { calls: 180060, avgLatency: 0.02, errorRate: 0, qps: 1800 },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "10",
    name: "ad_domain",
    type: "matcher",
    pluginKind: "qname",
    status: "running",
    enabled: true,
    pinned: false,
    config: { args: ["&/etc/oxidns/ad_domains.txt"] },
    metrics: { calls: 180060, avgLatency: 0.01, errorRate: 0, qps: 1800 },
    createdAt: "2024-01-16T14:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "11",
    name: "ip_cn",
    type: "matcher",
    pluginKind: "resp_ip",
    status: "running",
    enabled: true,
    pinned: false,
    config: { args: ["$cn_ip_set"] },
    metrics: { calls: 53500, avgLatency: 0.03, errorRate: 0, qps: 535 },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-19T11:20:00Z",
  },
  {
    id: "12",
    name: "hosts_local",
    type: "executor",
    pluginKind: "hosts",
    status: "running",
    enabled: true,
    pinned: true,
    config: { files: ["/etc/hosts"] },
    metrics: {
      calls: 5200,
      hitRate: 0.15,
      avgLatency: 0.01,
      errorRate: 0,
      qps: 52,
    },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "13",
    name: "redis_cache",
    type: "provider",
    pluginKind: "domain_set",
    status: "running",
    enabled: true,
    pinned: false,
    config: { files: ["/etc/oxidns/domains.txt"] },
    metrics: {
      calls: 275060,
      hitRate: 0.92,
      avgLatency: 0.5,
      errorRate: 0.001,
      qps: 2750,
    },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "14",
    name: "metrics_prometheus",
    type: "provider",
    pluginKind: "ip_set",
    status: "stopped",
    enabled: false,
    pinned: false,
    config: { files: ["/etc/oxidns/ips.txt"] },
    metrics: { calls: 0, avgLatency: 0, errorRate: 0, qps: 0 },
    createdAt: "2024-01-17T09:00:00Z",
    updatedAt: "2024-01-17T09:00:00Z",
  },
];

export const mockSystemMetrics: SystemMetrics = {
  totalPlugins: mockPlugins.length,
  runningPlugins: mockPlugins.filter((p) => p.status === "running").length,
  cpuUsage: 23.5,
  memoryUsage: 512,
  memoryTotal: 2048,
  currentQps: 1786,
  uptime: 864000,
};

export const mockSystemInfo: SystemInfo = {
  version: "1.2.3",
  latestVersion: "1.2.4",
  os: "Linux",
  arch: "x86_64",
  threads: 8,
  maxConcurrency: 10000,
  logLevel: "info",
  logRolling: "daily",
};

export const pluginKinds: Record<string, string[]> = {
  server: ["udp_server", "tcp_server", "http_server", "quic_server"],
  executor: [
    "sequence",
    "forward",
    "cache",
    "fallback",
    "hosts",
    "arbitrary",
    "redirect",
    "ecs_handler",
    "forward_edns0opt",
    "ttl",
    "prefer_ipv4",
    "prefer_ipv6",
    "black_hole",
    "drop_resp",
    "reverse_lookup",
    "query_summary",
    "query_recorder",
    "metrics_collector",
    "debug_print",
    "sleep",
    "http_request",
    "script",
    "ipset",
    "nftset",
    "ros_address_list",
    "upgrade",
    "download",
    "reload_provider",
    "reload",
    "cron",
  ],
  matcher: [
    "any_match",
    "qname",
    "question",
    "qtype",
    "qclass",
    "client_ip",
    "resp_ip",
    "ptr_ip",
    "cname",
    "rcode",
    "has_resp",
    "has_wanted_ans",
    "mark",
    "env",
    "random",
    "rate_limiter",
    "string_exp",
    "_true",
    "_false",
  ],
  provider: ["domain_set", "geosite", "adguard_rule", "ip_set", "geoip"],
};
