#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10

PROG=/usr/bin/oxidns
CONFIG=/etc/oxidns/config.yaml
WORKDIR=/var/lib/oxidns
HELPER=/usr/libexec/oxidns-openwrt

extra_command "show_password" "Print the generated OxiDNS WebUI/API password"
extra_command "reset_password" "Generate a new OxiDNS WebUI/API password"

start_service() {
	"$HELPER" init-config || return 1
	mkdir -p "$WORKDIR"

	procd_open_instance
	procd_set_param command "$PROG" start -c "$CONFIG" -d "$WORKDIR"
	procd_set_param file "$CONFIG"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	restart
}

show_password() {
	"$HELPER" show-password
}

reset_password() {
	"$HELPER" reset-password
}
